SET FOREIGN_KEY_CHECKS = 0;

-- DELETE DATA
TRUNCATE TABLE order_items;
TRUNCATE TABLE orders;
TRUNCATE TABLE users;

-- RESET AUTO_INCREMENT (automatic na ginagawa ng TRUNCATE, pero safe na rin)
ALTER TABLE order_items AUTO_INCREMENT = 1;
ALTER TABLE orders AUTO_INCREMENT = 1;
ALTER TABLE users AUTO_INCREMENT = 1;

SET FOREIGN_KEY_CHECKS = 1;
